### ISSUE TITLE
There is no commonComponent package 

### ISSUE THREAD

**Issue by AbhidnyaS09** [MadFlasheroo7/Compose-Animations#1]
![Screenshot 2024-09-22 at 5 25 49 PM](https://github.com/user-attachments/assets/1b661751-70da-4cf8-9fcd-6cb45f0dd4b9)

**Comment by MadFlasheroo7** [comment]
Hey @EvilHydra09 this project uses locally built common modules these are unpolished and highly experimental thus cant be published to maven central as of now u can follow the instructions at the module repo to build it locally 
https://github.com/MadFlasheroo7/Mad-App-Modules

thank you for reminding me I have updated the readme and contribution guidelines 
sry for the inconvience

**Comment by MadFlasheroo7** [comment]
added contribution guideline and updated me [here](https://github.com/MadFlasheroo7/Compose-Animations/commit/89870b8c5bf2e2e4a7e881767796a5a96ea40412)
